apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gamemetrics

resources:
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/name: data-retention-service
  app.kubernetes.io/part-of: gamemetrics
