apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - kafka-ui.yaml

commonLabels:
  app.kubernetes.io/name: kafka-ui
  app.kubernetes.io/part-of: gamemetrics
