apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - kafka-node-pools.yaml
  - kafka.yaml
  - topics.yaml

commonLabels:
  app.kubernetes.io/part-of: gamemetrics
  environment: base
