apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - https://strimzi.io/install/latest?namespace=kafka

commonLabels:
  app.kubernetes.io/part-of: gamemetrics
  app.kubernetes.io/managed-by: kustomize
