apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd-image-updater-system
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater-controller
data:
  log.level: info
  argocd.grpc_web: "true"
  argocd.insecure: "true"
  argocd.plaintext: "false"
  argocd.server_addr: "argocd-server.argocd.svc.cluster.local"
  registries.conf: |
    registries:
    - name: ECR
      api_url: https://647523695124.dkr.ecr.us-east-1.amazonaws.com
      prefix: 647523695124.dkr.ecr.us-east-1.amazonaws.com
      credentials: ext:/scripts/aws-ecr-creds.sh
      credsexpire: 10h
  applications_api: "argocd"
