apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application-kafka-prod.yaml
  - application-kafka-dev.yaml
  - application-event-ingestion-prod.yaml
  - application-event-ingestion-dev.yaml
  - application-notification-service-dev.yaml
  - application-event-consumer-logger-dev.yaml
