apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gamemetrics

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: event-processor-service
  app.kubernetes.io/part-of: gamemetrics
