apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus-rbac.yaml
  - prometheus-config-updated.yaml
  - prometheus-deployment.yaml
  - prometheus-alert-rules.yaml
  - grafana-config.yaml
  - grafana-deployment.yaml
  - loki-config.yaml
  - loki-deployment.yaml
  - promtail-config.yaml
  - promtail-daemonset.yaml
  - alertmanager-config.yaml
  - alertmanager-deployment.yaml
